image: node:18

deploy_dev:
  stage: deploy
  script:
    - |
      npm install -g @spaship/cli react-app-rewired
      npm ci
      SITEMAP_BASE_URL=https://developers.dev.redhat.com/apidocs npm run sitemap
      npm run build
      spaship deploy --env=$SPASHIP_DEV_WEB_PROPERTY --apikey=$SPASHIP_DEV_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  tags:
    - shared
    - docker

deploy_stage:
  stage: deploy
  script:
    - |
      npm install -g @spaship/cli react-app-rewired
      npm ci
      SITEMAP_BASE_URL=https://developers.stage.redhat.com/apidocs npm run sitemap
      npm run build
      spaship deploy --env=$SPASHIP_STAGE_WEB_PROPERTY --apikey=$SPASHIP_STAGE_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  tags:
    - shared
    - docker

deploy_qa:
  stage: deploy
  script:
    - |
      npm install -g @spaship/cli react-app-rewired
      npm ci
      SITEMAP_BASE_URL=https://developers.qa.redhat.com/apidocs npm run sitemap
      npm run build
      spaship deploy --env=$SPASHIP_QA_WEB_PROPERTY --apikey=$SPASHIP_QA_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  tags:
    - shared
    - docker
