image: node:18

deploy_dev:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
      libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
      libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
      libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
      libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
      libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
      xdg-utils wget libnss3 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0
      libxdamage1 libxcomposite1 libxfixes3 libxrandr2 libgbm1
  script:
    - |
      npm install -g @spaship/cli react-app-rewired
      npm ci
      SITEMAP_BASE_URL=https://developers.dev.redhat.com/apidocs npm run sitemap
      npm run build
      npm run prerender
      spaship deploy --env=$SPASHIP_DEV_WEB_PROPERTY --apikey=$SPASHIP_DEV_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  tags:
    - shared
    - docker

deploy_stage:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
      libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
      libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
      libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
      libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
      libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
      xdg-utils wget libnss3 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0
      libxdamage1 libxcomposite1 libxfixes3 libxrandr2 libgbm1
  script:
    - |
      npm install -g @spaship/cli react-app-rewired
      npm ci
      SITEMAP_BASE_URL=https://developers.stage.redhat.com/apidocs npm run sitemap
      npm run build
      npm run prerender
      spaship deploy --env=$SPASHIP_STAGE_WEB_PROPERTY --apikey=$SPASHIP_STAGE_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
      allow_failure: true
  tags:
    - shared
    - docker

deploy_qa:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
      libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
      libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
      libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
      libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
      libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
      xdg-utils wget libnss3 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0
      libxdamage1 libxcomposite1 libxfixes3 libxrandr2 libgbm1
  script:
    - |
      npm install -g @spaship/cli react-app-rewired
      npm ci
      SITEMAP_BASE_URL=https://developers.qa.redhat.com/apidocs npm run sitemap
      npm run build
      npm run prerender
      spaship deploy --env=$SPASHIP_QA_WEB_PROPERTY --apikey=$SPASHIP_QA_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
      allow_failure: true
  tags:
    - shared
    - docker
