apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/api-documentation-frontend?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/blob/main/pipelines/docker-build-oci-ta.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: api-documentation-frontend
    appstudio.openshift.io/component: api-documentation-frontend
    pipelines.appstudio.openshift.io/type: build
  name: api-documentation-frontend-on-push
  namespace: rh-platform-experien-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-platform-experien-tenant/api-documentation-frontend:{{revision}}
  - name: dockerfile
    value: ./Dockerfile
  - name: build-container-additional-secret
    value: api-documentation-frontend-sitemap
  pipelineRef:
    name: docker-build-oci-ta
  taskRunTemplate:
    serviceAccountName: build-pipeline-api-documentation-frontend
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
