# This workflow will review the current status of the APIs. It will verify if the API is:
#  - Reachable, i.e. we can download it.
#  - Following OpenapiV3+

name: Sync discovery

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.NACHO_BOT_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - id: discovery
      run: npm run discovery
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.NACHO_BOT_TOKEN }}
        title: Syncing API
        body: |
          There were some changes in the discovery or the contents of the APIs.
          
          Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
        commit-message: Syncing API
        delete-branch: true
        author: "GitHub <noreply@github.com>"
    - name: Auto-merge PR
      if: steps.cpr.outputs.pull-request-number != ''
      run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --squash
      env:
        GH_TOKEN: ${{ secrets.NACHO_BOT_TOKEN }}
